---
driver:
  name: ec2
  require_chef_omnibus: true
  #security_group_ids: ["sg-faf87683"]
  block_device_mappings:
    - ebs_device_name: /dev/sda1
      ebs_volume_size: 50
      ebs_delete_on_termination: true
transport:
  ssh_key: /home/atg/.ssh/id_rsa
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: redhat-7.2
    driver:
      image_id: ami-2051294a
      #instance_type: t2.micro
    transport:
      username: root
  #- name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ssh::default]
      - recipe[python::default]
      - recipe[git::default]
      - recipe[ureka::default]
    attributes: 
      ssh:
        options': {'Compression': 'yes', 'ForwardX11': 'yes', 'X11UseLocalhost': 'yes', 'UsePAM': 'no'}
