---
driver:
  name: vagrant
  use_sudo: false

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: cent7

suites:
  - name: default
    run_list:
      - recipe[eurka::default]
    attributes: {'ssh:' { 'options': {'Compression': 'yes', 'ForwardX11': 'yes'}}}
