name 'ureka'
maintainer 'Harvard ATG'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ureka'
long_description 'Installs/Configures ureka'
version '0.1.0'

depends 'yum', '~> 3.5.2'
depends 'ssh', '~> 0.10.10'
depends 'python', '~> 1.4.6'
